#!/usr/bin/env bash

# Configure HAproxy so that it send traffic to web-01 and web-02 using roundrobin

sudo apt-get update
sudo apt-get upgrade
sudo apt-get -y install haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original2
echo "	
listen  54.175.188.59
	bind 0:80
	mode http
	stats enable
	balance roundrobin
	option httpclose
	option forwardfor
	server 165194-web-01 54.167.147.167:80 check
	server 165194-web-02 100.25.117.132:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
