#!/usr/bin/env bash
# script that displays To infinity and beyond indefinitely.
#+ with a sleep 2 between each iteration
 
while true
do
  echo 'To infinity and beyond'
  sleep 2
  trap 'echo "I am invicible!!!"' SIGTERM
done
